version: '2.3'
services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform
      args:
        - KUBECTL_VERSION=${KUBECTL_VERSION:-v1.23.6}
        - HELM_VERSION=${HELM_VERSION:-v3.8.2}
        - USER=${USER}
    user: ${CURRENT_UID}
    image: terraform-docker:azavea-k8s
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/home/$USER/.aws:ro
      - $HOME/.kube:/home/$USER/.kube
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - AWS_PROFILE
      - AWS_DEFAULT_REGION
      - USER
      - ENVIRONMENT
      - DEBUG
      - EDITOR=vi
      - S3_SETTINGS_BUCKET=${S3_SETTINGS_BUCKET:-azavea-k8s-settings}
    working_dir: /usr/local/src
    entrypoint: bash
